grafana:
  enabled: true
  service:
    type: ClusterIP
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
  grafana.ini: |
    [paths]
    deleteDatasources = Loki
  sidecar:
    dashboards:
      enabled: true
prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true
alertmanager:
  enabled: true
