apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-circle
resources:
  - ../../base
images:
  - name: ahmed63/devops-circle-frontend
    newTag: d074fbe515433a81f46974135558e5f6e2b3180f
  - name: ahmed63/devops-circle-auth-service
    newTag: d074fbe515433a81f46974135558e5f6e2b3180f
  - name: ahmed63/devops-circle-user-service
    newTag: d074fbe515433a81f46974135558e5f6e2b3180f
  - name: ahmed63/devops-circle-post-service
    newTag: d074fbe515433a81f46974135558e5f6e2b3180f
  - name: ahmed63/devops-circle-like-service
    newTag: d074fbe515433a81f46974135558e5f6e2b3180f
  - name: ahmed63/devops-circle-comment-service
    newTag: d074fbe515433a81f46974135558e5f6e2b3180f
  - name: ahmed63/devops-circle-analytics-service
    newTag: d074fbe515433a81f46974135558e5f6e2b3180f
  - name: ahmed63/devops-circle-worker-service
    newTag: d074fbe515433a81f46974135558e5f6e2b3180f
patches:
  - target:
      kind: Ingress
      name: devops-circle-ingress
    patch: |-
      - op: add
        path: /spec/rules/-
        value:
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: frontend
                    port:
                      number: 80
