apiVersion: v1
kind: Secret
metadata:
  name: devops-circle-secret
  namespace: devops-circle
type: Opaque
stringData:
  POSTGRES_PASSWORD: ***REMOVED***
  DATABASE_URL: ***REMOVED***
  JWT_SECRET: ***REMOVED***
