apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-circle-fastapi-services
  namespace: devops-circle
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - devops-circle
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - auth-service
          - user-service
          - post-service
          - like-service
          - comment-service
          - analytics-service
  endpoints:
    - port: http
      path: /prometheus
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-circle-worker-service
  namespace: devops-circle
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - devops-circle
  selector:
    matchLabels:
      app: worker-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
